# Generated by Django 4.1.4 on 2022-12-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(default='', max_length=30)),
                ('nom_capitaine', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(default='', max_length=30)),
                ('nom', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=100)),
                ('numero_tel', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rencontre', models.CharField(default='', max_length=50)),
                ('lieu', models.CharField(default='', max_length=30)),
                ('date_match', models.DateField(null=True, verbose_name='date du match')),
                ('but_equipe_receveuse', models.IntegerField(default=0)),
                ('but_equipe_visiteuse', models.IntegerField(default=0)),
                ('equipe_receveuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_eq_rec', to='annonay_loisirs.equipe')),
                ('equipe_visiteuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_eq_vis', to='annonay_loisirs.equipe')),
            ],
        ),
    ]
