# Generated by Django 4.1.4 on 2022-12-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonay_loisirs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='annonay_loisirs.equipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nom_capitaine',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
