# Generated by Django 4.1.4 on 2022-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonay_loisirs', '0002_participant_equipe_alter_equipe_nom_capitaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='nom_rencontre',
        ),
    ]
