# Generated by Django 4.1.4 on 2022-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonay_loisirs', '0003_remove_match_nom_rencontre'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='aller_ou_retour',
            field=models.CharField(choices=[('aller', 'Match aller'), ('retour', 'Match retour')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='résultat',
            field=models.CharField(choices=[('gagné', 'Gagné'), ('nul', 'Nul'), ('perdu', 'Perdu')], max_length=50, null=True, verbose_name='résultat locaux'),
        ),
    ]
